import { type NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import AboutButton from "../components/AboutButton"
import Controls from "../components/Controls"
import ListModal from "../components/ListModal"
import PlayerContainer from "../components/PlayerContainer"
import RealPlayer from "../components/RealPlayer"
import Splash from "../components/Splash"
import usePlayersStore from "../store/players-store"

const Home: NextPage = () => {
	const [isPlaying, setIsPlayerVisible] = usePlayersStore((state) => [
		state.isPlaying,
		state.setIsPlaying,
	])
	const [isListOpen, setIsListOpen] = useState(false)
	const [isSplashOn, setIsSplashOn] = useState(true)

	const handleCloseList = () => {
		setIsListOpen(false)
	}

	const handleOpenList = () => {
		setIsListOpen(true)
		setTimeout(() => setIsPlayerVisible(false), 500)
	}
	const splashTimer = setTimeout(() => {
		setIsSplashOn(false)
	}, 1000)

	useEffect(() => {
		return () => {
			clearTimeout(splashTimer)
		}
	}, [splashTimer])

	return (
		<>
			<Head>
				<title>S2합작 커스텀 매시업버젼</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="fixed flex min-h-screen w-screen flex-col items-center justify-center bg-black">
				{isPlaying && <RealPlayer width={globalThis.innerWidth - 32} />}
				<PlayerContainer />
				<Controls openList={handleOpenList} />
				<ListModal isOpen={isListOpen} onClose={handleCloseList} />
			</main>
			{!isPlaying && <AboutButton />}
			<Splash isSplashOn={isSplashOn} />
		</>
	)
}

export default Home
