import { type NextPage } from "next"
import Head from "next/head"
import { Controls } from "../components/Controls"
import { useState } from "react"
import SelectModal from "../components/SelectModal"
import PlayerContainer from "../components/PlayerContainer"

const Home: NextPage = () => {
	const [isPlayerVisible, setIsPlayerVisible] = useState(true)
	const [isSelectOpen, setIsSelectOpen] = useState(false)

	const handleCloseSelect = () => {
		setIsSelectOpen(false)
		setIsPlayerVisible(true)
	}

	const handleOpenSelect = () => {
		setIsSelectOpen(true)
		setTimeout(() => setIsPlayerVisible(false), 500)
	}

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="fixed flex min-h-screen w-screen flex-col items-center justify-center bg-black">
				<PlayerContainer isVisible={isPlayerVisible} />
				<Controls openSelect={handleOpenSelect} />
				<SelectModal isOpen={isSelectOpen} onClose={handleCloseSelect} />
			</main>
		</>
	)
}

export default Home
