import { type NextPage } from "next"
import Head from "next/head"
import { Video } from "../components/Video"
import { Controls } from "../components/Controls"

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-black">
				<div className="container grid grid-cols-2 items-center justify-center justify-items-center px-4 py-16">
					<Video />
					<Video />
					<Video />
					<Video />
				</div>
				<Controls></Controls>
			</main>
		</>
	)
}

export default Home
